src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

   

    /**
     * @ORM\Column(type="string", length=10)
      * @Assert\Length(
     *      min = 10,
     *      max = 11,
     *      minMessage = "Phone must be at least {{ limit }} characters long",
     *      maxMessage = "Phone cannot be longer than {{ limit }} characters"
     * )
     */
    private $Phone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Address;

    /**
     * @ORM\OneToMany(targetEntity=Cart::class, mappedBy="usercart")
     */
    private $usercart;

    /**
     * @ORM\OneToMany(targetEntity=Order::class, mappedBy="userorder")
     */
    private $orderpro;

    public function __construct()
    {
        $this->usercart = new ArrayCollection();
        $this->orderpro = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->Phone;
    }

    public function setPhone(string $Phone): self
    {
        $this->Phone = $Phone;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(string $Address): self
    {
        $this->Address = $Address;

        return $this;
    }

    /**
     * @return Collection<int, Cart>
     */
    public function getUsercart(): Collection
    {
        return $this->usercart;
    }

    public function addUsercart(Cart $usercart): self
    {
        if (!$this->usercart->contains($usercart)) {
            $this->usercart[] = $usercart;
            $usercart->setUsercart($this);
        }

        return $this;
    }

    public function removeUsercart(Cart $usercart): self
    {
        if ($this->usercart->removeElement($usercart)) {
            // set the owning side to null (unless already changed)
            if ($usercart->getUsercart() === $this) {
                $usercart->setUsercart(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Order>
     */
    public function getOrderpro(): Collection
    {
        return $this->orderpro;
    }

    public function addOrderpro(Order $orderpro): self
    {
        if (!$this->orderpro->contains($orderpro)) {
            $this->orderpro[] = $orderpro;
            $orderpro->setUserorder($this);
        }

        return $this;
    }

    public function removeOrderpro(Order $orderpro): self
    {
        if ($this->orderpro->removeElement($orderpro)) {
            // set the owning side to null (unless already changed)
            if ($orderpro->getUserorder() === $this) {
                $orderpro->setUserorder(null);
            }
        }

        return $this;
    }
}

src/Controller/ManagerController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Entity\Supplier;
use App\Entity\User;
use App\Form\brandType;
use App\Form\EditBrand;
use App\Repository\OrderRepository;
use App\Repository\ProductRepository;
use App\Repository\SupplierRepository;
use App\Repository\UserRepository;
use Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
date_default_timezone_set('Asia/Ho_Chi_Minh');

class ManagerController extends AbstractController
{
    /**
     * @Route("/manager/product", name="managerProduct")
     */
    public function managerPro(ProductRepository $repo,SupplierRepository $brand): Response
    {
        $pro = $repo->findAll();
        $BR = $brand->findAll();
        return $this->render('manager/product.html.twig', [
            'pro'=>$pro, 'brand' => $BR
        ]);
    }

    /**
     * @Route("/manager/Account", name="managerAccount")
     */
    public function managerAcc(UserRepository $repo,SupplierRepository $brand): Response
    {
        $acc = $repo->findAll();
        $BR = $brand->findAll();
        return $this->render('manager/account.html.twig', [
            'acc'=>$acc, 'brand' => $BR
        ]);
    }
     /**
     * @Route("/manager/Brand", name="managerBrand")
     */
    public function managerbrand(SupplierRepository $brand): Response
    {
        ;
        $BR = $brand->findAll();
        return $this->render('manager/brand.html.twig', [
             'brand' => $BR
        ]);
    }

    /**
     * @Route("manager/brand/delete/{id}",name="delete_brand", requirements={"id"="\d+"})
     */
    
     public function deleteAction(SupplierRepository $repo, Supplier $b): Response
     {
        try {
            $repo->remove($b,true);
        } catch (ForeignKeyConstraintViolationException $th) {
            return $this->redirectToRoute('errForm', [], Response::HTTP_SEE_OTHER);
        }
         return $this->redirectToRoute('managerBrand', [], Response::HTTP_SEE_OTHER);
    }
    /**
     * @Route("manager/addbrand", name="addbrand")
     */
    public function addbrand(Request $req, SupplierRepository $repo, SupplierRepository $brand): Response
    {
        $BR = $brand->findAll();
         $s = new Supplier();
        $form = $this->createForm(brandType::class,$s);
        $form->handleRequest($req);
        if($form->isSubmitted()&&$form->isValid()){
            $repo->add($s,true);
            return $this->redirectToRoute('managerBrand', [], Response::HTTP_SEE_OTHER);

        }
        return $this->render('manager/addbrand.html.twig',[
            'form'=>$form->createView(), 'brand' => $BR
            ]);
    }
    /**
     * @Route("/errForm", name="errForm")
     */
    public function ERROR(SupplierRepository $brand): Response
    {
        $BR = $brand->findAll();
        return $this->render('manager/Error.html.twig', [
            'brand' => $BR
        ]);
    }
      /**
     * @Route("/manager/bill", name="managerBill")
     */
    public function managerbill(SupplierRepository $brand, OrderRepository $repo): Response
    {
        $oid = $repo->managerbill();
        $BR = $brand->findAll();
        return $this->render('manager/Bill.html.twig', [
             'brand' => $BR,'oid'=>$oid
        ]);
    }
    /**
     * @Route("/view/{id}", name="viewbill")
     */
    public function view(SupplierRepository $brand, OrderRepository $order, ProductRepository $pro,
    UserRepository $user, Order $o): Response
    {
       
        $BR = $brand->findAll();
        $total = $order->totaldetail($o);
        $viewdate = $order->viewdate($o);
        $billproduct = $order->billproduct($o);
        $billdetail = $order->billdetail($o);
        return $this->render('manager/viewbill.html.twig', ['brand' => $BR, 'billdetail'=>$billdetail,'billproduct'=>$billproduct,'date'=>$viewdate,
        'total'=>$total, 'oid'=>$o
    ]);
    }
    /**
     * @Route("/editbrand/{id}", name="editbrand")
     */
    public function editbrand(Request $req, SupplierRepository $repo, Supplier $s): Response
    {
        $BR = $repo->findAll();
        $form = $this->createForm(EditBrand::class,$s);
        $form->handleRequest($req);
        if($form->isSubmitted()&&$form->isValid()){
            $repo->add($s,true);
            return $this->redirectToRoute('managerBrand', [], Response::HTTP_SEE_OTHER);
        }
        return $this->render('manager/editbrand.html.twig',[
            'form'=>$form->createView(),'brand' => $BR
            ]);
    }
}

templates/manager/Bill.html.twig
{% extends 'base.html.twig' %}
{% block title %}Customer's bill{% endblock %}
{% block body %}
    <h1>Bill list</h1>
    
    <table class="table">
        <thead>
            <tr>
                <th>No.</th>
                {# <th>Name</th> #}
                <th>Total</th>
                <th>Date</th>
                {# <th>Addess</th> #}
                <th>Action</th>


                
            </tr>
        </thead>
        <tbody>
         {% for a in oid %}
            <tr>
                <td>{{ a.id}}</td>
                {# <td>{{ a.Name }}</td> #}
                <td>{{ a.Total }}</td>
                <td>{{ a.Date|date('d/m/Y H:i') }}</td>
                <td><a href="{{ path('viewbill', { 'id': a.id }) }}">View</a></td>
                {# <td> 
                
                    <a href="{{ path('viewbill', { 'id': a.id }) }}">Delete</a>
                    
                </td> #}
               
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/manager/Error.html.twig
{% extends 'base.html.twig' %}
{% block title %}ERROR{% endblock %}
{% block body %}
<div class="container-fluid" style ="background:rgb(237,67,55);
    height:500px"> 

 <div class= "row">
 <div style="margin-top:130px">
     <i class="fa-solid fa-circle-exclamation" style="font-size:100px;
     margin-left:630px; margin-bottom:50px"></i>
         <h1 style = "
           text-align:center;
           color:white">Error! An error occurred. Please try again later</h1>
 </div>
 </div>
   </div>
 
{% endblock %}

templates/manager/account.html.twig
{% extends 'base.html.twig' %}
{% block title %}Manager Customer Account{% endblock %}
{% block body %}
    <h1>Account List</h1>
    
    <table class="table">
        <thead>
            <tr>
                <th>No.</th>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Addess</th>
                {# <th>Action</th> #}


                
            </tr>
        </thead>
        <tbody>
         {% for a in acc %}
            <tr>
                <td>{{ a.id}}</td>
                <td>{{ a.name }}</td>
                <td>{{ a.Email }}</td>
                <td>{{ a.phone }}</td>
                <td>{{ a.Address}}</td>
                {# <td> 
                
                    <a href="{{ path('account_delete', { 'id': a.id }) }}">Delete</a>
                    
                </td> #}
               
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/manager/addbrand.html.twig
{% extends 'base.html.twig' %}
{% block title %}Add Brand{% endblock %}
{% block body %}
    <div class="container">

        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
        {# <button href>Back</button> #} <button style ="border-radius:10px;
    margin-bottom : 20px;
    background:rgb(0, 149,246,0.3);
    border:1px solid white;
    "><a href ="{{path('managerBrand')}}">Back to Manager Brand</a></button>
    </div>
{% endblock %}

templates/manager/brand.html.twig
{% extends 'base.html.twig' %}
{% block title %}Manager Brand{% endblock %}
{% block body %}
    <h1>Product List</h1>
    <button style ="border-radius:10px;
    margin-bottom : 20px;
    background:rgb(0, 149,246,0.3);
    border:1px solid white;
    "><a href ="{{path('addbrand')}}">Add Brand</a></button>
    <table class="table">
        <thead>
            <tr>
                <th>No.</th>
                <th>Name</th>
                <th>Actions</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
         {% for p in brand %}
            <tr>
                <td>{{ p.id }}</td>
                <td>{{ p.namesup }}</td>
                
                <td>
                    <a href="{{ path('editbrand', { 'id': p.id }) }}">Edit</a>
                    
                </td>
                 <td>
                    <a href="{{ path('delete_brand', { 'id': p.id }) }}"><i class="fa-solid fa-trash-can"></i></a>
                    
                </td>
               
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/manager/editbrand.html.twig
{% extends 'base.html.twig' %}
{% block title %}Edit Brand{% endblock %}
{% block body %}
    <div class="container">
        {{ form_start(form) }}
        <label>Supplier's Name</label>
        {{ form_widget(form.namesup) }}
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/manager/product.html.twig
{% extends 'base.html.twig' %}
{% block title %}Manager Product{% endblock %}
{% block body %}
    <h1>Product List</h1>
    <button style ="border-radius:10px;
    margin-bottom : 20px;
    background:rgb(0, 149,246,0.3);
    border:1px solid white;
    " ><a href ="{{path('addproduct')}}">Add Product</a></button>
    <table class="table">
        <thead>
            <tr>
                <th>No.</th>
                <th>ID Product</th>
                <th>Name</th>
                <th>Price</th>
                <th>Actions</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
         {% for p in pro %}
            <tr>
                <td>{{ p.id }}</td>
                <td>{{ p.idpro }}</td>
                <td>{{ p.namepro }}</td>
                <td>{{ p.price}}</td>
                <td>
                    <a href="{{ path('edit', { 'id': p.id }) }}">Edit</a>
                    
                </td>
                 <td>
                    <a href="{{ path('product_delete', { 'id': p.id }) }}"><i class="fa-solid fa-trash-can"></i></a>
                    
                </td>
               
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/manager/viewbill.html.twig
   {% extends 'base.html.twig' %}
{% block title %}Customer's Bill Detail{% endblock %}
{% block body %}

    <style>
        
        
        article{
           width : 800px;
            padding-top: 30px;
            margin: auto;
            background-color: #fff;
            height: auto;
        }
       article h1{
        text-align: center;
       }
       
        
       
        
    </style>
   <article>
            {# <h1>Successful</h1> #}
            <hr>
            {% for d in date %}
              <p style ="margin-top:30px"> Date : {{d.Date|date('d/m/Y H:i')}}</p>  
            {% endfor %}
            
            {# <p>{{date}}</p> #}
            {% for o in oid %}
              <p>Order's ID :{{o.id}}</p>  
            {% endfor %}
            

             <div class="infor ">
             {% for u in billdetail %}
            <p  style ="margin-top:30px; margin-bottom:30px"> Name : {{u.Name}}</p>
             {% endfor %}
           
             </div>
            <hr>
            <div class="bill">
                <table class="table">
                <tr> 
                <th>Item</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Total</th>

                                           
                </tr>
                {% for p in billproduct %}
                 <tr> 
                  
                 <td>{{p.namepro}}</td> 
                <td> 
               <h6 class="mb-0"><span>{{p.Quantity}}</span> </h6>
                </td>
                <td><h6 class="mb-0"><span>${{p.price}}</span> </h6>
                </td> 
                <td>
                <h6 class="mb-0"><span>${{sum(p.Quantity,p.price)}}</span> </h6>
                </td>
                 </tr>
                 {% endfor %}
                        
                                     
                 <tr>
                <td colspan="3">Total</td>
                     {% for t in total %}                    
                <td style = "margin-right:30px">${{t.Total}}</td>
                {% endfor %} 
                </tr>
                
                                              
                </table> 
                
                </div>
            </div>
            <h6 class="my-5" ><a href="{{path('app_test')}}" class="text-body">Back to shop <i class="bi bi-box-arrow-left me-2"></i></a></h6> 

        </article>

        
{% endblock %}